# Generated by Django 5.0.6 on 2024-05-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(max_length=255)),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('genero_cliente', models.CharField(max_length=255)),
                ('tipo_cliente', models.CharField(max_length=255)),
                ('profesion_cliente', models.CharField(max_length=255)),
                ('estado_civil_cliente', models.CharField(max_length=255)),
                ('nacionalidad_cliente', models.CharField(max_length=255)),
                ('tipo_direccion_cliente', models.CharField(max_length=255)),
                ('tipo_vivienda_cliente', models.CharField(max_length=255)),
                ('tipo_parroquia_residencia_trabajo_cliente', models.CharField(max_length=255)),
                ('pais_residencia_trabajo_cliente', models.CharField(max_length=255)),
                ('provincia_residencia_trabajo_cliente', models.CharField(max_length=255)),
                ('canton_residencia_trabajo_cliente', models.CharField(max_length=255)),
                ('parroquia_residencia_trabajo_cliente', models.CharField(max_length=255)),
                ('barrio_residencia_trabajo_cliente', models.CharField(max_length=255)),
                ('calle_principal_residencia_trabajo_cliente', models.CharField(max_length=255)),
                ('calle_secundaria_residencia_trabajo_cliente', models.CharField(max_length=255)),
                ('referencia_residencia_trabajo_cliente', models.TextField()),
                ('nivel_educacion_cliente', models.CharField(max_length=255)),
                ('producto_principal', models.CharField(max_length=255)),
                ('latitud_domicilio', models.FloatField(blank=True, null=True)),
                ('longitud_domicilio', models.FloatField(blank=True, null=True)),
                ('latitud_trabajo', models.FloatField(blank=True, null=True)),
                ('longitud_trabajo', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
