# Generated by Django 5.0.6 on 2024-05-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='referencia_residencia_trabajo_cliente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
