# Generated by Django 5.0.6 on 2024-05-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_cliente_latitud_domicilio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='latitud_trabajo',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='longitud_trabajo',
            field=models.CharField(blank=True, null=True),
        ),
    ]
