# Generated by Django 5.0.6 on 2024-06-13 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_cliente_latitud_trabajo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitas', models.PositiveIntegerField(default=0)),
                ('visitasExitosas', models.PositiveIntegerField(default=0)),
                ('visitasNoExitosas', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cliente')),
            ],
        ),
    ]
